version: "2.1"
services:
  opbeans-java:
    build: .
    image: opbeans/opbeans-java:latest
    ports:
      - "127.0.0.1:${OPBEANS_SERVER_PORT:-8000}:3000"
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-java}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
      - ELASTIC_APM_APPLICATION_PACKAGES=co.elastic.apm.opbeans
      - ELASTIC_APM_JS_SERVER_URL=http://localhost:${APM_SERVER_PORT:-8200}
      - OPBEANS_SERVER_PORT=3000
      - ELASTIC_APM_FLUSH_INTERVAL=5
      - ELASTIC_APM_TRANSACTION_MAX_SPANS=50
      - ELASTIC_APM_SAMPLE_RATE=1
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OPBEANS_DT_PROBABILITY=0.50
      - OPBEANS_SERVICES=opbeans-java
    depends_on:
      elasticsearch:
        condition: service_healthy
      apm-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:3000/"]
      interval: 10s
      retries: 10

  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION:-6.6.0}
    ports:
      - "127.0.0.1:${APM_SERVER_PORT:-8200}:8200"
      - "127.0.0.1:${APM_SERVER_MONITOR_PORT:-6060}:6060"
    command: >
      apm-server -e
        --httpprof ':6060'
        -E apm-server.rum.enabled=true
        -E apm-server.rum.event_rate.limit=1000
        -E apm-server.frontend.rate_limit=100000
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.read_timeout=1m
        -E apm-server.shutdown_timeout=2m
        -E apm-server.write_timeout=1m
        -E logging.json=true
        -E logging.metrics.enabled=false
        -E xpack.monitoring.elasticsearch=true
        -E xpack.monitoring.enabled=true
        -E setup.dashboards.enabled=false
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
        -E output.elasticsearch.enabled=true
        -E "output.elasticsearch.pipelines=[{pipeline: 'apm_user_agent'}]"
        -E apm-server.register.ingest.pipeline.enabled=true
    cap_add: [CHOWN, DAC_OVERRIDE, SETGID, SETUID]
    cap_drop: [ALL]
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:8200/"]
      retries: 10
      interval: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-6.6.0}
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g"
      - "path.data=/usr/share/elasticsearch/data/6.6.0"
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/backups,
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 5g
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - "127.0.0.1:${ELASTICSEARCH_PORT:-9200}:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      retries: 10
      interval: 20s
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-6.6.0}
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: 'true'
      XPACK_XPACK_MAIN_TELEMETRY_ENABLED: 'false'
    ports:
      - "127.0.0.1:${KIBANA_PORT:-5601}:5601"
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://kibana:5601/"]
      retries: 10
      interval: 10s
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  esdata:
    driver: local
